dinerTicket/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #pointing to apps URL mapper
    url(r'^',include('www.urls'))
]

www/urls.py
from django.conf.urls import url
from . import views

app_name = 'www'
urlpatterns = [
	url(r'^$',views.IndexView.as_view(),name='index'),
	url(r'^restaurant/(?P<pk>[0-9]+)/$',views.RestaurantView.as_view(),name='restaurant')
]

www/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
'''
This options basically helps track number of days!
WEEK_DAYS = (
    (1, 'Monday'),
    (2, 'Tuesday'),
    (3, 'Wednesday'),
    (4, 'Thursday'),
    (5, 'Friday'),
    (6, 'Saturday'),
    (7, 'Sunday'),
)
'''
class Restaurant(models.Model):
	restaurant_name = models.CharField(max_length=100)
	email = models.EmailField(max_length=254, unique=True)
	about = models.CharField(max_length = 500)
	banner = models.CharField(max_length=500)
	last_modified = models.DateField(auto_now=False)
	

	def __str__(self):
		return self.restaurant_name

www/views.py
from django.shortcuts import render
from .models import Restaurant
from django.views import generic
# Create your views here.
#def index(request):
	#returning all restaurant object in a restaurants context, which can be accessed in the index.html file. Yes o.
#	return render(request,'index.html',{'restaurants': Restaurant.objects.all()})

class IndexView(generic.ListView):
	template_name = "index.html"
	context_object_name = "restaurants"

	def get_queryset(self):
		return Restaurant.objects.all()

class RestaurantView(generic.DetailView):
	model = Restaurant
	template_name = "restaurant.html"

www/templates/index.html
{% load staticfiles %}
<doctype html>
<html>
	<head>
		<title>
			Welcome to diner ticket
		</title>
		<link rel="stylesheet" href="{% static 'style.css' %}"/>
	</head>
	<body>
		<main>
			<section class="header">
				<center><h1>DINERTICKET.COM</h1></center>
			</section>
			<section class="section_mama">
				{% for restaurant in restaurants %}
				<section class="restaurant_card">
					<img src="{{ restaurant.banner }}" />
					<p class="title">{{restaurant.restaurant_name}}</p>
					<p class="about">{{ restaurant.about}}</p>
				</section>
				{% endfor %}
			</section>
		</main>

	</body>

www/templates/restaurant.html
{% load staticfiles %}
<doctype html>
<html>
	<head>
		<title>
			Welcome to {{restaurant.restaurant_name}}
		</title>
		<link rel="stylesheet" href="{% static 'style.css' %}"/>
	</head>
	<body>
		<center>
		<main>
			<section class="section_mama_detail">
				<section class="restaurant_card">
					<img src="{{ restaurant.banner }}" />
					<p class="title">{{restaurant.restaurant_name}}</p>
					<p class="about">{{ restaurant.about}}</p>
				</section>
				<section>
				<a href="{% url 'www:index' %}"> BACK </a>
				</section>
			</section>
		</main>
		</center>
	</body>